// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository_interface.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/repository_interface.go -destination internal/mocks/repository_mocks.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Nakohartum/gophermart-loyalty-system/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AuthenticateUser mocks base method.
func (m *MockRepository) AuthenticateUser(ctx context.Context, login, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateUser indicates an expected call of AuthenticateUser.
func (mr *MockRepositoryMockRecorder) AuthenticateUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockRepository)(nil).AuthenticateUser), ctx, login, password)
}

// CreateOrder mocks base method.
func (m *MockRepository) CreateOrder(ctx context.Context, order model.Order, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockRepositoryMockRecorder) CreateOrder(ctx, order, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockRepository)(nil).CreateOrder), ctx, order, userID)
}

// GetCurrentUserBalance mocks base method.
func (m *MockRepository) GetCurrentUserBalance(ctx context.Context, userID int64) model.BalanceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUserBalance", ctx, userID)
	ret0, _ := ret[0].(model.BalanceResponse)
	return ret0
}

// GetCurrentUserBalance indicates an expected call of GetCurrentUserBalance.
func (mr *MockRepositoryMockRecorder) GetCurrentUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUserBalance", reflect.TypeOf((*MockRepository)(nil).GetCurrentUserBalance), ctx, userID)
}

// GetListOfUploadedOrders mocks base method.
func (m *MockRepository) GetListOfUploadedOrders(ctx context.Context, userID int64) []model.OrderResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListOfUploadedOrders", ctx, userID)
	ret0, _ := ret[0].([]model.OrderResponse)
	return ret0
}

// GetListOfUploadedOrders indicates an expected call of GetListOfUploadedOrders.
func (mr *MockRepositoryMockRecorder) GetListOfUploadedOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListOfUploadedOrders", reflect.TypeOf((*MockRepository)(nil).GetListOfUploadedOrders), ctx, userID)
}

// GetOrdersForProcessing mocks base method.
func (m *MockRepository) GetOrdersForProcessing(ctx context.Context) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForProcessing", ctx)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForProcessing indicates an expected call of GetOrdersForProcessing.
func (mr *MockRepositoryMockRecorder) GetOrdersForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForProcessing", reflect.TypeOf((*MockRepository)(nil).GetOrdersForProcessing), ctx)
}

// GetWithdrawalsInfo mocks base method.
func (m *MockRepository) GetWithdrawalsInfo(ctx context.Context, userID int64) []model.Withdrawal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsInfo", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	return ret0
}

// GetWithdrawalsInfo indicates an expected call of GetWithdrawalsInfo.
func (mr *MockRepositoryMockRecorder) GetWithdrawalsInfo(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsInfo", reflect.TypeOf((*MockRepository)(nil).GetWithdrawalsInfo), ctx, userID)
}

// RegisterUser mocks base method.
func (m *MockRepository) RegisterUser(ctx context.Context, login, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockRepositoryMockRecorder) RegisterUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockRepository)(nil).RegisterUser), ctx, login, password)
}

// UpdateOrder mocks base method.
func (m *MockRepository) UpdateOrder(ctx context.Context, userID int64, number string, status model.Status, accrual *float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, userID, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockRepositoryMockRecorder) UpdateOrder(ctx, userID, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockRepository)(nil).UpdateOrder), ctx, userID, number, status, accrual)
}

// WithdrawBalance mocks base method.
func (m *MockRepository) WithdrawBalance(ctx context.Context, request model.WithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBalance", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawBalance indicates an expected call of WithdrawBalance.
func (mr *MockRepositoryMockRecorder) WithdrawBalance(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBalance", reflect.TypeOf((*MockRepository)(nil).WithdrawBalance), ctx, request)
}
