// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/db/storage_interface.go
//
// Generated by this command:
//
//	mockgen -source internal/config/db/storage_interface.go -destination internal/mocks/storage_mocks.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Nakohartum/gophermart-loyalty-system/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AuthenticateUser mocks base method.
func (m *MockStorage) AuthenticateUser(ctx context.Context, login, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateUser indicates an expected call of AuthenticateUser.
func (mr *MockStorageMockRecorder) AuthenticateUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockStorage)(nil).AuthenticateUser), ctx, login, password)
}

// CheckConnection mocks base method.
func (m *MockStorage) CheckConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnection indicates an expected call of CheckConnection.
func (mr *MockStorageMockRecorder) CheckConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnection", reflect.TypeOf((*MockStorage)(nil).CheckConnection), ctx)
}

// CloseConnection mocks base method.
func (m *MockStorage) CloseConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockStorageMockRecorder) CloseConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockStorage)(nil).CloseConnection), ctx)
}

// CreateOrder mocks base method.
func (m *MockStorage) CreateOrder(ctx context.Context, order model.Order, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStorageMockRecorder) CreateOrder(ctx, order, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStorage)(nil).CreateOrder), ctx, order, userID)
}

// GetCurrentUserBalance mocks base method.
func (m *MockStorage) GetCurrentUserBalance(ctx context.Context, userID int64) model.BalanceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUserBalance", ctx, userID)
	ret0, _ := ret[0].(model.BalanceResponse)
	return ret0
}

// GetCurrentUserBalance indicates an expected call of GetCurrentUserBalance.
func (mr *MockStorageMockRecorder) GetCurrentUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUserBalance", reflect.TypeOf((*MockStorage)(nil).GetCurrentUserBalance), ctx, userID)
}

// GetListOfUploadedOrders mocks base method.
func (m *MockStorage) GetListOfUploadedOrders(ctx context.Context, userID int64) []model.OrderResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListOfUploadedOrders", ctx, userID)
	ret0, _ := ret[0].([]model.OrderResponse)
	return ret0
}

// GetListOfUploadedOrders indicates an expected call of GetListOfUploadedOrders.
func (mr *MockStorageMockRecorder) GetListOfUploadedOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListOfUploadedOrders", reflect.TypeOf((*MockStorage)(nil).GetListOfUploadedOrders), ctx, userID)
}

// GetOrdersForProcessing mocks base method.
func (m *MockStorage) GetOrdersForProcessing(ctx context.Context) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForProcessing", ctx)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForProcessing indicates an expected call of GetOrdersForProcessing.
func (mr *MockStorageMockRecorder) GetOrdersForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForProcessing", reflect.TypeOf((*MockStorage)(nil).GetOrdersForProcessing), ctx)
}

// GetWithdrawalsInfo mocks base method.
func (m *MockStorage) GetWithdrawalsInfo(ctx context.Context, userID int64) []model.Withdrawal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsInfo", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	return ret0
}

// GetWithdrawalsInfo indicates an expected call of GetWithdrawalsInfo.
func (mr *MockStorageMockRecorder) GetWithdrawalsInfo(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsInfo", reflect.TypeOf((*MockStorage)(nil).GetWithdrawalsInfo), ctx, userID)
}

// OpenConnection mocks base method.
func (m *MockStorage) OpenConnection(ctx context.Context, databaseURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenConnection", ctx, databaseURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenConnection indicates an expected call of OpenConnection.
func (mr *MockStorageMockRecorder) OpenConnection(ctx, databaseURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenConnection", reflect.TypeOf((*MockStorage)(nil).OpenConnection), ctx, databaseURI)
}

// RegisterUser mocks base method.
func (m *MockStorage) RegisterUser(ctx context.Context, login, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockStorageMockRecorder) RegisterUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockStorage)(nil).RegisterUser), ctx, login, password)
}

// UpdateOrder mocks base method.
func (m *MockStorage) UpdateOrder(ctx context.Context, userID int64, number string, status model.Status, accrual *float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, userID, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockStorageMockRecorder) UpdateOrder(ctx, userID, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockStorage)(nil).UpdateOrder), ctx, userID, number, status, accrual)
}

// WithdrawBalance mocks base method.
func (m *MockStorage) WithdrawBalance(ctx context.Context, request model.WithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBalance", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawBalance indicates an expected call of WithdrawBalance.
func (mr *MockStorageMockRecorder) WithdrawBalance(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBalance", reflect.TypeOf((*MockStorage)(nil).WithdrawBalance), ctx, request)
}
